services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: socketfi_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - socketfi_history_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d socketfi_history"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  socketfi_history_pg:
